FROM ubuntu:18.04

RUN sed -i 's|http://archive.ubuntu.com|http://us-west-1.ec2.archive.ubuntu.com|g' /etc/apt/sources.list

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
  && apt-get install -y \
  build-essential \
  g++ \
  cmake \
  liblcms2-dev \
  libtiff-dev \
  libpng-dev \
  libz-dev

WORKDIR /workdir

CMD [ "./build-x86.sh" ]
