FROM ubuntu:18.04

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
  && apt-get install -y \
  build-essential \
  g++ \
  cmake \
  liblcms2-dev \
  libtiff-dev \
  libpng-dev \
  libz-dev

WORKDIR /workdir

CMD [ "./build-x86.sh" ]
